# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7636459965893e2397740e0474f02ed7847e18d7cc122da79371a9a29a41bf0c53e1dd96f4d304d7788f9b2a42f1b8aa7eaca4b4edf4b0a7430458da9db156ae

test:
  secret_key_base: cf5673ad5bf76101e8c5069ffc77cec7615e3618aa1fae1e27e7712cf07926b1b069c43be443ecda0f5ceee64c1f4cfb9dfc86db0766df2cffc7325312a6de97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || SecureRandom.uuid %>
